version: "3.8"

services:
  frontend:
    image: quangvinh1601/jlearn_fe_app:latest
    ports:
      - "80:80"
    volumes:
      - /home/nguyenhuuquangvinh/jlearn_fe_app/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true
